name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # A versão do Python que seu projeto usa
  - pytest       # Pacote de testes
  - flake8       # Linter para garantir a qualidade do código
  - pip
  - pip:
    - attrs==25.3.0
    - boto3==1.40.22
    - botocore==1.40.22
    - certifi==2025.7.14
    - charset-normalizer==3.4.3
    - distlib==0.4.0
    - filelock==3.18.0
    - h11==0.16.0
    - idna==3.10
    - jmespath==1.0.1
    - MouseInfo==0.1.3
    - numpy==2.2.6
    - opencv-python==4.12.0.88
    - outcome==1.3.0.post0
    - pillow==11.3.0
    - platformdirs==4.3.8
    - PyAutoGUI==0.9.54
    - pycparser==2.22
    - pygame==2.6.1
    - PyGetWindow==0.0.9
    - PyMsgBox==1.0.9
    - pyperclip==1.9.0
    - PyRect==0.2.0
    - PyScreeze==1.0.1
    - python-dateutil==2.9.0.post0
    - pytweening==1.2.0
    - qrcode==8.2
    - requests==2.32.5
    - s3transfer==0.13.1
    - selenium==4.34.2
    - six==1.17.0
    - sniffio==1.3.1
    - sortedcontainers==2.4.0
    - trio==0.30.0
    - trio-websocket==0.12.2
    - typing_extensions==4.14.1
    - virtualenv==20.32.0
    - websocket-client==1.8.0
    - wsproto==1.2.0